package dev.joaomendonca.agendapro.appointment.application;
import dev.joaomendonca.agendapro.appointment.api.*;import dev.joaomendonca.agendapro.appointment.domain.*;import dev.joaomendonca.agendapro.appointment.infrastructure.*;import dev.joaomendonca.agendapro.customer.domain.*;import dev.joaomendonca.agendapro.customer.infrastructure.*;import dev.joaomendonca.agendapro.employee.domain.*;import dev.joaomendonca.agendapro.employee.infrastructure.*;import dev.joaomendonca.agendapro.service.domain.*;import dev.joaomendonca.agendapro.service.infrastructure.*;import dev.joaomendonca.agendapro.shared.exception.*;import dev.joaomendonca.agendapro.shared.security.AuthenticatedTenantProvider;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class AppointmentService{
 private static final UUID CREATE_SENTINEL=new UUID(0,0);private final AppointmentRepository appointments;private final CustomerRepository customers;private final EmployeeRepository employees;private final ServiceOfferingRepository services;private final EmployeeBlockRepository blocks;private final AuthenticatedTenantProvider tenant;
 public AppointmentService(AppointmentRepository a,CustomerRepository c,EmployeeRepository e,ServiceOfferingRepository s,EmployeeBlockRepository b,AuthenticatedTenantProvider t){appointments=a;customers=c;employees=e;services=s;blocks=b;tenant=t;}
 @Transactional public AppointmentResponse create(AppointmentRequest r){UUID tid=tenant.tenantId();Refs refs=refs(tid,r);LocalDateTime end=r.startsAt().plusMinutes(refs.service.getDurationMinutes());validate(tid,r.employeeId(),r.startsAt(),end,CREATE_SENTINEL);return response(appointments.save(new Appointment(tid,r.customerId(),r.employeeId(),r.serviceId(),r.startsAt(),end,r.notes(),refs.service.getPrice())),refs);}
 @Transactional(readOnly=true) public List<AppointmentResponse> list(LocalDate from,LocalDate to){UUID tid=tenant.tenantId();LocalDate start=from==null?LocalDate.now():from;LocalDate end=to==null?start.plusDays(7):to;return appointments.findAllByTenantIdAndStartsAtBetweenOrderByStartsAt(tid,start.atStartOfDay(),end.plusDays(1).atStartOfDay()).stream().map(this::response).toList();}
 @Transactional(readOnly=true) public AppointmentResponse get(UUID id){return response(find(id));}
 @Transactional public AppointmentResponse update(UUID id,AppointmentRequest r){Appointment a=find(id);Refs refs=refs(a.getTenantId(),r);LocalDateTime end=r.startsAt().plusMinutes(refs.service.getDurationMinutes());validate(a.getTenantId(),r.employeeId(),r.startsAt(),end,id);a.update(r.customerId(),r.employeeId(),r.serviceId(),r.startsAt(),end,r.notes(),refs.service.getPrice());return response(a,refs);}
 @Transactional public AppointmentResponse status(UUID id,AppointmentStatusRequest r){Appointment a=find(id);a.changeStatus(r.status());return response(a);}
 private void validate(UUID tid,UUID employeeId,LocalDateTime start,LocalDateTime end,UUID ignored){if(!end.isAfter(start))throw new DomainException("INVALID_APPOINTMENT_PERIOD","O horário final deve ser posterior ao inicial.");if(appointments.hasConflict(tid,employeeId,start,end,ignored))throw new ConflictException("APPOINTMENT_CONFLICT","O profissional já possui um agendamento neste horário.");if(blocks.existsConflict(employeeId,start.atZone(ZoneId.systemDefault()).toInstant(),end.atZone(ZoneId.systemDefault()).toInstant()))throw new ConflictException("EMPLOYEE_BLOCK_CONFLICT","O profissional possui um bloqueio neste horário.");}
 private Refs refs(UUID tid,AppointmentRequest r){Customer c=customers.findByIdAndTenantId(r.customerId(),tid).filter(x->x.getStatus()==CustomerStatus.ACTIVE).orElseThrow(()->new NotFoundException("CUSTOMER_NOT_FOUND","Cliente ativo não encontrado."));Employee e=employees.findByIdAndTenantId(r.employeeId(),tid).filter(x->x.getStatus()==EmployeeStatus.ACTIVE).orElseThrow(()->new NotFoundException("EMPLOYEE_NOT_FOUND","Funcionário ativo não encontrado."));ServiceOffering s=services.findByIdAndTenantId(r.serviceId(),tid).filter(x->x.getStatus()==ServiceStatus.ACTIVE).orElseThrow(()->new NotFoundException("SERVICE_NOT_FOUND","Serviço ativo não encontrado."));return new Refs(c,e,s);}
 private Appointment find(UUID id){return appointments.findByIdAndTenantId(id,tenant.tenantId()).orElseThrow(()->new NotFoundException("APPOINTMENT_NOT_FOUND","Agendamento não encontrado."));}
 private AppointmentResponse response(Appointment a){UUID tid=a.getTenantId();return response(a,new Refs(customers.findByIdAndTenantId(a.getCustomerId(),tid).orElseThrow(),employees.findByIdAndTenantId(a.getEmployeeId(),tid).orElseThrow(),services.findByIdAndTenantId(a.getServiceId(),tid).orElseThrow()));}
 private AppointmentResponse response(Appointment a,Refs r){return new AppointmentResponse(a.getId(),a.getCustomerId(),r.customer.getName(),a.getEmployeeId(),r.employee.getName(),a.getServiceId(),r.service.getName(),a.getStartsAt(),a.getEndsAt(),a.getStatus(),a.getNotes(),a.getPrice(),a.getCreatedAt(),a.getUpdatedAt());}
 private record Refs(Customer customer,Employee employee,ServiceOffering service){}
}
