package dev.joaomendonca.agendapro.finance.application;
import dev.joaomendonca.agendapro.finance.api.*;import dev.joaomendonca.agendapro.finance.domain.*;import dev.joaomendonca.agendapro.finance.infrastructure.*;import dev.joaomendonca.agendapro.shared.exception.*;import dev.joaomendonca.agendapro.shared.security.AuthenticatedTenantProvider;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;
@Service public class FinanceService{private final FinancialTransactionRepository repo;private final AuthenticatedTenantProvider tenant;public FinanceService(FinancialTransactionRepository r,AuthenticatedTenantProvider t){repo=r;tenant=t;}
 @Transactional public FinancialTransactionResponse create(FinancialTransactionRequest r){return map(repo.save(new FinancialTransaction(tenant.tenantId(),r.type(),r.category(),r.description(),r.amount(),r.occurredOn(),r.status())));}
 @Transactional(readOnly=true) public List<FinancialTransactionResponse> list(LocalDate from,LocalDate to){LocalDate f=from==null?LocalDate.now().withDayOfMonth(1):from;LocalDate t=to==null?f.plusMonths(1).minusDays(1):to;return repo.findAllByTenantIdAndOccurredOnBetweenOrderByOccurredOnDesc(tenant.tenantId(),f,t).stream().map(this::map).toList();}
 @Transactional public FinancialTransactionResponse update(UUID id,FinancialTransactionRequest r){FinancialTransaction x=find(id);x.update(r.type(),r.category(),r.description(),r.amount(),r.occurredOn(),r.status());return map(x);}
 @Transactional public void delete(UUID id){repo.delete(find(id));}
 @Transactional(readOnly=true) public FinanceSummaryResponse summary(LocalDate from,LocalDate to){var items=list(from,to);BigDecimal income=items.stream().filter(x->x.type()==TransactionType.INCOME&&x.status()==TransactionStatus.PAID).map(FinancialTransactionResponse::amount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal expenses=items.stream().filter(x->x.type()==TransactionType.EXPENSE&&x.status()==TransactionStatus.PAID).map(FinancialTransactionResponse::amount).reduce(BigDecimal.ZERO,BigDecimal::add);long pending=items.stream().filter(x->x.status()==TransactionStatus.PENDING).count();return new FinanceSummaryResponse(income,expenses,income.subtract(expenses),pending);}
 private FinancialTransaction find(UUID id){return repo.findByIdAndTenantId(id,tenant.tenantId()).orElseThrow(()->new NotFoundException("TRANSACTION_NOT_FOUND","Lançamento financeiro não encontrado."));} private FinancialTransactionResponse map(FinancialTransaction x){return new FinancialTransactionResponse(x.getId(),x.getType(),x.getCategory(),x.getDescription(),x.getAmount(),x.getOccurredOn(),x.getStatus(),x.getCreatedAt(),x.getUpdatedAt());}}
