import { Cake, MessageCircle, MoreHorizontal, Plus, Search, SlidersHorizontal, UserRound, UsersRound } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Toast } from '../components/Toast'
import { api, ApiError } from '../services/api'
import type { Customer, CustomerRequest, CustomerStatus } from '../types'
import { CustomerDetailsModal } from './customers/CustomerDetailsModal'
import { CustomerFormModal } from './customers/CustomerFormModal'

function upcomingBirthday(date:string|null){if(!date)return false;const [,m,d]=date.split('-').map(Number);const now=new Date();const current=new Date(now.getFullYear(),m-1,d);if(current<new Date(now.getFullYear(),now.getMonth(),now.getDate()))current.setFullYear(now.getFullYear()+1);return (current.getTime()-now.getTime())/86400000<=30}
export function CustomersPage(){
 const [customers,setCustomers]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[status,setStatus]=useState<'ALL'|CustomerStatus>('ALL'),[editing,setEditing]=useState<Customer|null|'new'>(null),[details,setDetails]=useState<Customer|null>(null),[toast,setToast]=useState<{message:string;type?:'success'|'error'}|null>(null)
 const load=async()=>{setLoading(true);try{setCustomers(await api.listCustomers())}catch(e){setToast({message:e instanceof ApiError?e.message:'Não foi possível carregar os clientes.',type:'error'})}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),3200);return()=>window.clearTimeout(t)},[toast])
 const filtered=useMemo(()=>customers.filter(c=>`${c.name} ${c.email||''} ${c.phone||''}`.toLowerCase().includes(search.toLowerCase())&&(status==='ALL'||c.status===status)),[customers,search,status])
 const birthdays=customers.filter(c=>c.status==='ACTIVE'&&upcomingBirthday(c.birthDate)).length
 const save=async(payload:CustomerRequest)=>{try{if(editing==='new'){await api.createCustomer(payload);setToast({message:'Cliente cadastrado com sucesso.'})}else if(editing){await api.updateCustomer(editing.id,payload);setToast({message:'Cliente atualizado com sucesso.'})}setEditing(null);await load()}catch(e){setToast({message:e instanceof ApiError?e.message:'Não foi possível salvar.',type:'error'});throw e}}
 const changeStatus=async(c:Customer)=>{const next:CustomerStatus=c.status==='ACTIVE'?'INACTIVE':'ACTIVE';try{const updated=await api.changeCustomerStatus(c.id,next);setDetails(updated);await load();setToast({message:next==='ACTIVE'?'Cliente reativado.':'Cliente inativado.'})}catch(e){setToast({message:e instanceof ApiError?e.message:'Não foi possível alterar o status.',type:'error'})}}
 return <><div className="page-heading"><div><span className="eyebrow neutral">RELACIONAMENTO</span><h1>Clientes</h1><p>Centralize contatos, aniversários e informações importantes.</p></div><button className="button primary" onClick={()=>setEditing('new')}><Plus size={18}/> Novo cliente</button></div>
 <div className="mini-stats"><div><span className="stat-icon"><UsersRound size={20}/></span><p><small>Total de clientes</small><strong>{customers.length}</strong></p></div><div><span className="stat-icon"><UserRound size={20}/></span><p><small>Clientes ativos</small><strong>{customers.filter(c=>c.status==='ACTIVE').length}</strong></p></div><div><span className="stat-icon"><Cake size={20}/></span><p><small>Aniversários em 30 dias</small><strong>{birthdays}</strong></p></div></div>
 <section className="panel employee-panel"><div className="toolbar"><div className="search-box"><Search size={18}/><input placeholder="Buscar por nome, e-mail ou telefone..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-group"><SlidersHorizontal size={17}/><select value={status} onChange={e=>setStatus(e.target.value as 'ALL'|CustomerStatus)}><option value="ALL">Todos os status</option><option value="ACTIVE">Ativos</option><option value="INACTIVE">Inativos</option></select></div></div>
 {loading?<div className="loading-state"><span className="spinner"/> Carregando clientes...</div>:filtered.length===0?<div className="empty-state"><span><UsersRound size={32}/></span><h3>{customers.length?'Nenhum cliente encontrado':'Sua base de clientes começa aqui'}</h3><p>{customers.length?'Tente alterar os filtros da busca.':'Cadastre o primeiro cliente para manter o relacionamento organizado.'}</p>{!customers.length&&<button className="button primary" onClick={()=>setEditing('new')}><Plus size={18}/> Cadastrar cliente</button>}</div>:<div className="employee-table-wrap"><table className="employee-table"><thead><tr><th>CLIENTE</th><th>CONTATO</th><th>ANIVERSÁRIO</th><th>STATUS</th><th>ATUALIZADO</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} onClick={()=>setDetails(c)}><td><div className="employee-cell"><span className="avatar employee-avatar"><UserRound size={19}/></span><div><strong>{c.name}</strong><small>ID {c.id.slice(0,8)}</small></div></div></td><td><div className="contact-cell"><span>{c.email||'E-mail não informado'}</span><small><MessageCircle size={12}/>{c.phone||'Telefone não informado'}</small></div></td><td>{c.birthDate?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',timeZone:'UTC'}).format(new Date(c.birthDate+'T00:00:00Z')):'—'}</td><td><span className={`badge ${c.status==='ACTIVE'?'success':'neutral'}`}><i/>{c.status==='ACTIVE'?'Ativo':'Inativo'}</span></td><td>{new Intl.DateTimeFormat('pt-BR').format(new Date(c.updatedAt))}</td><td><button className="icon-button" onClick={e=>{e.stopPropagation();setDetails(c)}}><MoreHorizontal size={19}/></button></td></tr>)}</tbody></table></div>}
 <footer className="table-footer"><span>{filtered.length} {filtered.length===1?'cliente':'clientes'}</span><span><Cake size={15}/> Aniversários destacados no resumo</span></footer></section>
 {editing&&<CustomerFormModal customer={editing==='new'?null:editing} onClose={()=>setEditing(null)} onSave={save}/>} {details&&<CustomerDetailsModal customer={details} onClose={()=>setDetails(null)} onEdit={()=>{setEditing(details);setDetails(null)}} onStatus={()=>void changeStatus(details)}/>} {toast&&<Toast {...toast}/>}</>
}
