import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Banknote, Bot, Building2, Calculator, Check, CircleDollarSign, Globe2, Landmark, MessageCircle, Plus, ReceiptText, ShoppingBag, WalletCards, X } from 'lucide-react'
import { api, ApiError } from '../services/api'
import { Modal } from '../components/Modal'
import { Toast } from '../components/Toast'
import type { BusinessUnit, CashSession, Customer, NotificationItem, ServiceOffering, ServiceOrder } from '../types'
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)
const dateTime=(v?:string)=>v?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—'
type Tab='orders'|'cash'|'whatsapp'|'assistant'|'units'|'online'
export function OperationsPage(){
 const [tab,setTab]=useState<Tab>('orders');const [orders,setOrders]=useState<ServiceOrder[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [services,setServices]=useState<ServiceOffering[]>([]);const [cash,setCash]=useState<CashSession>({status:'CLOSED'});const [notifications,setNotifications]=useState<NotificationItem[]>([]);const [units,setUnits]=useState<BusinessUnit[]>([]);const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');const [selectedOrder,setSelectedOrder]=useState<ServiceOrder|null>(null);const [openOrder,setOpenOrder]=useState(false);const [cashModal,setCashModal]=useState<'open'|'close'|null>(null);const [toast,setToast]=useState<{message:string;type?:'success'|'error'}|null>(null)
 const load=async()=>{try{const [o,c,s,ca,n,u]=await Promise.all([api.listOrders(),api.listCustomers(),api.listServices(),api.currentCash(),api.listNotifications(),api.listUnits()]);setOrders(o);setCustomers(c.filter(x=>x.status==='ACTIVE'));setServices(s.filter(x=>x.status==='ACTIVE'));setCash(ca);setNotifications(n);setUnits(u)}catch(e){setToast({message:e instanceof ApiError?e.message:'Erro ao carregar central operacional',type:'error'})}}
 useEffect(()=>{void load()},[])
 const opened=useMemo(()=>orders.filter(o=>o.status==='OPEN'),[orders]);const openTotal=opened.reduce((sum,o)=>sum+Number(o.total),0)
 const createOrder=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const created=await api.createOrder({customerId:String(fd.get('customerId')),notes:String(fd.get('notes')||'')});setOpenOrder(false);await load();const detail=await api.getOrder(created.id);setSelectedOrder(detail);setToast({message:'Comanda aberta com sucesso.'})}catch(error){setToast({message:error instanceof ApiError?error.message:'Erro ao abrir comanda',type:'error'})}}
 const openDetails=async(id:string)=>{try{setSelectedOrder(await api.getOrder(id))}catch(error){setToast({message:error instanceof ApiError?error.message:'Erro ao abrir comanda',type:'error'})}}
 const addItem=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selectedOrder)return;const fd=new FormData(e.currentTarget);const service=services.find(x=>x.id===String(fd.get('serviceId')));try{await api.addOrderItem(selectedOrder.id,{itemType:service?'SERVICE':'PRODUCT',referenceId:service?.id,description:service?.name||String(fd.get('description')),quantity:Number(fd.get('quantity')||1),unitPrice:service?.price||Number(fd.get('unitPrice'))});setSelectedOrder(await api.getOrder(selectedOrder.id));e.currentTarget.reset();await load()}catch(error){setToast({message:error instanceof ApiError?error.message:'Erro ao adicionar item',type:'error'})}}
 const closeOrder=async(paymentMethod:string)=>{if(!selectedOrder)return;try{await api.closeOrder(selectedOrder.id,paymentMethod);setSelectedOrder(null);await load();setToast({message:'Comanda finalizada e receita lançada no financeiro.'})}catch(error){setToast({message:error instanceof ApiError?error.message:'Erro ao finalizar comanda',type:'error'})}}
 const ask=async(e:FormEvent)=>{e.preventDefault();const r=await api.askAssistant(question);setAnswer(r.answer+(r.data.length?` (${r.data.length} resultado(s))`:''))}
 return <><div className="page-heading"><div><span className="eyebrow neutral">OPERAÇÃO PREMIUM</span><h1>Central operacional</h1><p>Controle comandas, caixa, pagamentos e automações do dia.</p></div></div><div className="tabs-row">{([['orders',ReceiptText,'Comandas'],['cash',Landmark,'Caixa'],['whatsapp',MessageCircle,'WhatsApp'],['assistant',Bot,'Assistente'],['units',Building2,'Unidades'],['online',Globe2,'Agendamento online']] as const).map(([id,Icon,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={17}/>{label}</button>)}</div>
 {tab==='orders'&&<><div className="operation-summary"><article><ShoppingBag/><span><small>Comandas abertas</small><strong>{opened.length}</strong></span></article><article><CircleDollarSign/><span><small>Valor em aberto</small><strong>{money(openTotal)}</strong></span></article><article><Check/><span><small>Finalizadas hoje</small><strong>{orders.filter(o=>o.status==='CLOSED'&&o.closedAt?.slice(0,10)===new Date().toISOString().slice(0,10)).length}</strong></span></article><button className="button primary" onClick={()=>setOpenOrder(true)}><Plus size={17}/>Abrir comanda</button></div><section className="content-card orders-board"><header><div><h2>Comandas</h2><p>Acompanhe consumo, itens e pagamento em tempo real.</p></div></header><div className="order-columns"><div><h3>Em atendimento <span>{opened.length}</span></h3><div className="order-card-list">{opened.map(o=><button className="order-card" key={o.id} onClick={()=>void openDetails(o.id)}><div><span className="status-live"><i/>Aberta</span><small>{dateTime(o.openedAt)}</small></div><h4>{o.customerName}</h4><strong>{money(Number(o.total))}</strong><span>Ver comanda →</span></button>)}{!opened.length&&<div className="empty-order">Nenhuma comanda aberta.</div>}</div></div><div><h3>Finalizadas recentemente</h3><div className="order-card-list compact">{orders.filter(o=>o.status==='CLOSED').slice(0,8).map(o=><button className="order-card closed" key={o.id} onClick={()=>void openDetails(o.id)}><div><span className="status-done"><Check size={12}/>Finalizada</span><small>{dateTime(o.closedAt)}</small></div><h4>{o.customerName}</h4><strong>{money(Number(o.total))}</strong><span>{o.paymentMethod||'Pagamento registrado'}</span></button>)}</div></div></div></section></>}
 {tab==='cash'&&<><div className="cash-hero"><div className={`cash-status-orb ${cash.status.toLowerCase()}`}><Landmark/></div><div><span className="eyebrow neutral">STATUS DO CAIXA</span><h2>{cash.status==='OPEN'?'Caixa aberto':'Caixa fechado'}</h2><p>{cash.status==='OPEN'?`Aberto em ${dateTime(cash.openedAt)}`:'Abra o caixa para iniciar as movimentações do expediente.'}</p></div>{cash.status==='CLOSED'?<button className="button primary" onClick={()=>setCashModal('open')}>Abrir caixa</button>:<button className="button secondary" onClick={()=>setCashModal('close')}>Fechar caixa</button>}</div>{cash.status==='OPEN'&&<div className="cash-grid"><article><WalletCards/><small>Saldo inicial</small><strong>{money(cash.openingBalance||0)}</strong></article><article className="positive"><Banknote/><small>Entradas de hoje</small><strong>{money(cash.incomeToday||0)}</strong></article><article className="negative"><ReceiptText/><small>Saídas de hoje</small><strong>{money(cash.expensesToday||0)}</strong></article><article className="featured"><Calculator/><small>Saldo esperado</small><strong>{money(cash.expectedBalance||0)}</strong></article></div>}<section className="content-card cash-guidance"><h3>Conferência de fechamento</h3><p>O saldo esperado considera o saldo inicial mais receitas pagas e menos despesas pagas do dia. Ao fechar, informe o valor contado para registrar possíveis diferenças.</p></section></>}
 {tab==='whatsapp'&&<section className="content-card"><header><div><h2>Lembretes por WhatsApp</h2><p>A fila está pronta; o envio real depende das credenciais do provedor.</p></div><button className="button primary" onClick={async()=>{const r=await api.queueReminders();setToast({message:r.message});await load()}}>Gerar lembretes</button></header><div className="ranking-list">{notifications.map(n=><div key={n.id}><b>WA</b><span>{n.recipient} · {n.template}</span><strong>{n.status}</strong></div>)}</div></section>}
 {tab==='assistant'&&<section className="content-card narrow-card"><header><div><h2>Assistente do negócio</h2><p>Pergunte sobre faturamento, clientes inativos e cancelamentos.</p></div></header><form onSubmit={ask} className="assistant-box"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Quais clientes não voltam há 90 dias?"/><button className="button primary">Perguntar</button></form>{answer&&<div className="assistant-answer">{answer}</div>}</section>}
 {tab==='online'&&<section className="content-card narrow-card"><header><div><h2>Página pública de agendamento</h2><p>Defina o endereço que seus clientes usarão para reservar horários.</p></div></header><form className="form-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api.updatePublicBookingSettings({enabled:true,slug:String(f.get('slug')),message:String(f.get('message'))});setToast({message:'Página pública ativada em /book/'+String(f.get('slug'))})}}><label className="field full-field">Identificador da página<input name="slug" required placeholder="salao-da-maria"/></label><label className="field full-field">Mensagem<textarea name="message" placeholder="Escolha o melhor horário para você."/></label><button className="button primary full-field">Publicar página</button></form></section>}
 {tab==='units'&&<section className="content-card"><header><div><h2>Multiunidade</h2><p>Base pronta para administrar filiais no mesmo tenant.</p></div></header><div className="ranking-list">{units.map(u=><div key={u.id}><b><Building2 size={15}/></b><span>{u.name}<small>{u.address}</small></span><strong>{u.active?'Ativa':'Inativa'}</strong></div>)}</div></section>}
 {openOrder&&<Modal title="Abrir nova comanda" subtitle="Selecione o cliente que está em atendimento." onClose={()=>setOpenOrder(false)}><form className="form-grid" onSubmit={createOrder}><label className="field full-field">Cliente<select name="customerId" required><option value="">Selecione</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field full-field">Observações<textarea name="notes" placeholder="Preferências, produtos separados, observações do atendimento…"/></label><div className="modal-actions full-field"><button type="button" className="button secondary" onClick={()=>setOpenOrder(false)}>Cancelar</button><button className="button primary">Abrir comanda</button></div></form></Modal>}
 {selectedOrder&&<Modal title={`Comanda · ${selectedOrder.customerName}`} subtitle={`Aberta em ${dateTime(selectedOrder.openedAt)}`} onClose={()=>setSelectedOrder(null)} wide><div className="order-detail-layout"><section><div className="order-total"><small>TOTAL DA COMANDA</small><strong>{money(Number(selectedOrder.total))}</strong><span className={selectedOrder.status==='OPEN'?'status-live':'status-done'}>{selectedOrder.status==='OPEN'?'Em atendimento':'Finalizada'}</span></div><div className="order-items"><header><h3>Itens</h3><span>{selectedOrder.items?.length||0} item(ns)</span></header>{selectedOrder.items?.length?selectedOrder.items.map(item=><article key={item.id}><div><strong>{item.description}</strong><small>{Number(item.quantity)} × {money(Number(item.unitPrice))}</small></div><b>{money(Number(item.total))}</b></article>):<div className="empty-order">Adicione serviços ou produtos à comanda.</div>}</div></section>{selectedOrder.status==='OPEN'&&<aside><form className="form-grid" onSubmit={addItem}><h3 className="full-field">Adicionar item</h3><label className="field full-field">Serviço<select name="serviceId"><option value="">Produto ou item avulso</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {money(s.price)}</option>)}</select></label><label className="field full-field">Descrição<input name="description" placeholder="Ex.: Shampoo profissional"/></label><label className="field">Quantidade<input name="quantity" type="number" min="0.01" step="0.01" defaultValue="1"/></label><label className="field">Valor unitário<input name="unitPrice" type="number" min="0" step="0.01" defaultValue="0"/></label><button className="button secondary full-field"><Plus size={16}/>Adicionar à comanda</button></form><div className="payment-actions"><h3>Finalizar pagamento</h3>{['PIX','CARTÃO','DINHEIRO'].map(method=><button key={method} onClick={()=>void closeOrder(method)}><WalletCards size={16}/>{method}</button>)}</div></aside>}</div></Modal>}
 {cashModal&&<Modal title={cashModal==='open'?'Abrir caixa':'Fechar caixa'} subtitle={cashModal==='open'?'Informe o dinheiro disponível no início do expediente.':`Saldo esperado: ${money(cash.expectedBalance||0)}`} onClose={()=>setCashModal(null)}><form className="form-grid" onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{if(cashModal==='open')await api.openCash(Number(fd.get('balance')));else await api.closeCash(cash.id!,Number(fd.get('balance')),String(fd.get('notes')||''));setCashModal(null);await load();setToast({message:cashModal==='open'?'Caixa aberto.':'Caixa fechado e conferido.'})}catch(error){setToast({message:error instanceof ApiError?error.message:'Erro ao atualizar caixa',type:'error'})}}}><label className="field full-field">{cashModal==='open'?'Saldo inicial':'Saldo contado'}<input name="balance" type="number" min="0" step="0.01" required autoFocus/></label>{cashModal==='close'&&<label className="field full-field">Observações<textarea name="notes" placeholder="Informe diferenças ou ocorrências do fechamento."/></label>}<div className="modal-actions full-field"><button type="button" className="button secondary" onClick={()=>setCashModal(null)}><X size={16}/>Cancelar</button><button className="button primary">Confirmar</button></div></form></Modal>}
 {toast&&<Toast {...toast}/>}</>}
