package dev.joaomendonca.agendapro.service.application;
import dev.joaomendonca.agendapro.service.api.*;import dev.joaomendonca.agendapro.service.domain.*;import dev.joaomendonca.agendapro.service.infrastructure.*;import dev.joaomendonca.agendapro.shared.exception.*;import dev.joaomendonca.agendapro.shared.security.AuthenticatedTenantProvider;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class ServiceOfferingService {private final ServiceOfferingRepository repository;private final AuthenticatedTenantProvider tenant;public ServiceOfferingService(ServiceOfferingRepository repository,AuthenticatedTenantProvider tenant){this.repository=repository;this.tenant=tenant;}
 @Transactional public ServiceResponse create(ServiceRequest r){UUID tid=tenant.tenantId();validate(tid,r.name(),null);return ServiceResponse.from(repository.save(new ServiceOffering(tid,r.name(),r.description(),r.durationMinutes(),r.price(),r.category(),r.commissionPercentage())));}
 @Transactional(readOnly=true) public List<ServiceResponse> list(){return repository.findAllByTenantIdOrderByName(tenant.tenantId()).stream().map(ServiceResponse::from).toList();}
 @Transactional(readOnly=true) public ServiceResponse get(UUID id){return ServiceResponse.from(find(id));}
 @Transactional public ServiceResponse update(UUID id,ServiceRequest r){ServiceOffering s=find(id);validate(s.getTenantId(),r.name(),id);s.update(r.name(),r.description(),r.durationMinutes(),r.price(),r.category(),r.commissionPercentage());return ServiceResponse.from(s);}
 @Transactional public ServiceResponse status(UUID id,ServiceStatusRequest r){ServiceOffering s=find(id);s.changeStatus(r.status());return ServiceResponse.from(s);}
 public ServiceOffering findEntity(UUID id){return find(id);} private ServiceOffering find(UUID id){return repository.findByIdAndTenantId(id,tenant.tenantId()).orElseThrow(()->new NotFoundException("SERVICE_NOT_FOUND","Serviço não encontrado."));}
 private void validate(UUID tid,String name,UUID id){boolean exists=id==null?repository.existsByTenantIdAndNameIgnoreCase(tid,name):repository.existsByTenantIdAndNameIgnoreCaseAndIdNot(tid,name,id);if(exists)throw new ConflictException("SERVICE_NAME_ALREADY_EXISTS","Já existe um serviço com este nome.");}}
